shell /usr/bin/zsh
kitty_mod ctrl+shift

# BEGIN_KITTY_THEME
# Solarized Dark Higher Contrast
include current-theme.conf
# END_KITTY_THEME

#FONTS
font_family CommitMono Nerd Font
bold_font CommitMono Nerd Font, Bold
italic_font CommitMono Nerd Font, Italic


font_size 10

#TRANSAPARANCY
background_opacity 0.9

#LAYOUT
enabled_layouts tall,*

#WINDOWS
window_margin_width 2
window_border_width 1pt
window_border_color #ffffff
active_border_color #ffffff
window_padding_width 12
draw_window_borders_for_single_window yes

#TABS
tab_bar_style powerline
tab_powerline_style slanted
tab_activity_symbol *  


#TITLE BAR
hide_window_decorations yes

#CURSOR
cursor  #00aeff
cursor_blink_interval 0.8
cursor_trail 1
cursor_trail_decay 0.1 0.2

remember_window_size no
initial_window_width  70c
initial_window_height 20c
